##secret 구성: RCLONE_CONFIG
name: vdlb

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  vdlb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.10'
          
      - name: Install dependencies
        run: |
          sudo apt update      
          curl https://rclone.org/install.sh | sudo bash
          echo "$RCLONE_CONFIG" > rclone.conf
          rclone --config rclone.conf copy "mydrive:github/vdlb" ./ --user-agent "ISV|rclone.org|rclone/v1.68.0"
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
          
      - name: Try to solve error
        run: export NEEDRESTART_MODE=l

      - name: Run setup script
        run: |
          chmod +x ./run.sh > /dev/null 2>&1
          ./run.sh > /dev/null 2>&1
        env:
          MY_TOKEN_1: ${{ secrets.MY_TOKEN_1 }}
          MY_TOKEN_2: ${{ secrets.MY_TOKEN_2 }}
